server.port=9050

spring.application.name=langchain4j-demo

# 模型参数 - 日志级别
logging.level.dev.langchain4j = DEBUG

# 流式输出字符编码，防止乱码
server.servlet.encoding.charset=utf-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# redis config，持久化
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.connect-timeout=3s
spring.data.redis.timeout=2s
