server.port=8010
spring.application.name=spring-ai-rag-agent

# sping ai 配置
spring.ai.openai.api-key=${deepseek-api}
spring.ai.openai.base-url=https://api.deepseek.com
spring.ai.openai.chat.options.model=deepseek-chat
